"""Command-line entry points for myoassist-terrains.

Subcommands:
  build <config.json>  [--activate]   Generate a terrain XML from a config.
  set-active <name>                    Switch the active terrain pointer.
  list                                 List available terrains in the library.
  preview <name>                       Emit a standalone wrapper for visualizer QC.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Sequence

from myoassist_terrains.composer import build_terrain, emit_xml_include
from myoassist_terrains.config import load_config
from myoassist_terrains.paths import (
    find_terrain_root,
    terrain_config_path,
    terrain_library_dir,
)
from myoassist_terrains.tiles import REGISTRY


# ---------------------------------------------------------------------------
# Build


def cmd_build(args: argparse.Namespace) -> int:
    config_path = Path(args.config).resolve()
    if not config_path.exists():
        print(f"error: config file not found: {config_path}", file=sys.stderr)
        return 2

    config = load_config(config_path)

    root = find_terrain_root()
    library = terrain_library_dir(root)
    library.mkdir(parents=True, exist_ok=True)

    spec = build_terrain(config, output_dir=library)
    xml = emit_xml_include(spec)

    out_path = library / f"{config.terrain_name}.xml"
    header = (
        "<!-- Generated by myoassist-terrains. Do not edit by hand; "
        "re-run `myoassist-terrains build` instead. -->\n"
    )
    out_path.write_text(header + xml + "\n", encoding="utf-8")
    print(f"Wrote {out_path.relative_to(root)}")

    if args.activate:
        _set_active(config.terrain_name)
    return 0


# ---------------------------------------------------------------------------
# Set-active


def cmd_set_active(args: argparse.Namespace) -> int:
    return _set_active(args.name)


def _set_active(name: str) -> int:
    root = find_terrain_root()
    library = terrain_library_dir(root)
    target = library / f"{name}.xml"
    if not target.exists():
        print(f"error: no such terrain: {target.relative_to(root)}", file=sys.stderr)
        print(f"       run `myoassist-terrains list` to see what's available.", file=sys.stderr)
        return 2

    config_path = terrain_config_path(root)
    text = config_path.read_text(encoding="utf-8")

    # Replace the second <include> line (the one pointing at terrain/...).
    # MuJoCo resolves nested <include> paths relative to the TOP-LEVEL model
    # file's directory, not relative to the file containing the <include>.
    # If terrain_config.xml lives one level above the consuming model files,
    # the path needs a "../" prefix to climb out of the model dir before
    # descending into terrain/. Match either "terrain/..." or
    # "../terrain/..." for compatibility with shallower layouts.
    new_path = f"../terrain/{name}.xml"
    new_text, n = re.subn(
        r'(<include\s+file=")(?:\.\./)?terrain/[^"]+(")',
        rf'\1{new_path}\2',
        text,
        count=1,
    )
    if n == 0:
        print(
            f"error: could not find an existing 'terrain/...' include line in "
            f"{config_path}. Aborting.",
            file=sys.stderr,
        )
        return 3

    config_path.write_text(new_text, encoding="utf-8")
    print(f"Active terrain set to {new_path}")
    return 0


# ---------------------------------------------------------------------------
# Preview


def cmd_preview(args: argparse.Namespace) -> int:
    """Emit a standalone <mujoco>-rooted wrapper that just loads a terrain.

    Useful for visual QC of a generated terrain WITHOUT loading a model.
    The wrapper lives inside the terrain library directory so the
    `../terrain_style.xml` chained-include in the terrain file resolves
    correctly when the wrapper is the top-level model file.
    """
    name = args.name
    root = find_terrain_root()
    library = terrain_library_dir(root)
    target = library / f"{name}.xml"
    if not target.exists():
        print(f"error: no such terrain: {target.relative_to(root)}", file=sys.stderr)
        print(f"       run `myoassist-terrains list` to see what's available.", file=sys.stderr)
        return 2

    out_path = library / f"{name}_preview.xml"
    wrapper = (
        f"<!-- Generated by `myoassist-terrains preview {name}`. Open this file in the\n"
        f"     MJ visualizer to inspect the generated terrain in isolation. -->\n"
        f'<mujoco model="{name}_preview">\n'
        f'    <include file="{name}.xml"/>\n'
        f"</mujoco>\n"
    )
    out_path.write_text(wrapper, encoding="utf-8")
    print(f"Wrote {out_path.relative_to(root)}")
    print(f"Open with: python -m mujoco.viewer --mjcf={out_path}")
    return 0


# ---------------------------------------------------------------------------
# List


def cmd_list(args: argparse.Namespace) -> int:
    root = find_terrain_root()
    library = terrain_library_dir(root)
    if not library.exists():
        print(f"(no terrain library yet at {library.relative_to(root)})")
        return 0

    config_text = terrain_config_path(root).read_text(encoding="utf-8")
    m = re.search(r'<include\s+file="(?:\.\./)?terrain/([^"]+)"', config_text)
    active = m.group(1) if m else None

    terrains = sorted(p.name for p in library.glob("*.xml"))
    if not terrains:
        print(f"(no terrains found in {library.relative_to(root)})")
        return 0

    print(f"Terrains in {library.relative_to(root)}:")
    for name in terrains:
        marker = "  *" if name == active else "   "
        print(f"{marker} {name}")
    if active:
        print(f"\nActive: terrain/{active}")
    print(f"\nRegistered tile types: {sorted(REGISTRY)}")
    return 0


# ---------------------------------------------------------------------------
# Dispatch


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="myoassist-terrains",
        description="Modular procedural terrain generator for MuJoCo.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_build = sub.add_parser("build", help="Build a terrain from a JSON config")
    p_build.add_argument("config", help="Path to a terrain config JSON file")
    p_build.add_argument(
        "--activate",
        action="store_true",
        help="Set the newly-built terrain as active after writing it",
    )
    p_build.set_defaults(func=cmd_build)

    p_setactive = sub.add_parser("set-active", help="Switch the active terrain")
    p_setactive.add_argument("name", help="Terrain name (without .xml)")
    p_setactive.set_defaults(func=cmd_set_active)

    p_list = sub.add_parser("list", help="List terrains in the library")
    p_list.set_defaults(func=cmd_list)

    p_preview = sub.add_parser(
        "preview",
        help="Emit a <mujoco>-rooted wrapper for visualizer-only terrain QC",
    )
    p_preview.add_argument("name", help="Terrain name (without .xml)")
    p_preview.set_defaults(func=cmd_preview)

    args = parser.parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
