"""Generate the tile catalog tables in `docs/tiles.md` from the registry.

The catalog was hand-maintained and drifted: `density` was documented as an area
fraction when it is a count per square meter, `boulders` were described as
half-spheres with a diameter range when they are ellipsoids taking radii, and
`rough`'s `vertical_relief` had a circular definition. Four of the review's
documentation findings were this one problem.

So the tables are generated. Each tile module owns its own `PARAM_DOCS`, next to
the `DEFAULT_PARAMS` and `PARAM_RANGES` the table reports, and the docs cannot
disagree with the code.

    python utils/docs/_gen_tile_catalog.py            # rewrite the catalog
    python utils/docs/_gen_tile_catalog.py --check     # fail if it is stale (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

from myoassist_terrains.tiles import REGISTRY  # noqa: E402  (needs the path above)

DOC = REPO / "docs" / "tiles.md"
BEGIN = "<!-- BEGIN GENERATED: tile-catalog -->"
END = "<!-- END GENERATED: tile-catalog -->"


def _summary(module_name: str) -> str:
    """First line of the tile module's docstring, minus the `<name> tile:` prefix."""
    import importlib

    module = importlib.import_module(f"myoassist_terrains.tiles.{module_name}")
    first = (module.__doc__ or "").strip().splitlines()[0].strip()
    marker = "tile:"
    if marker in first:
        first = first.split(marker, 1)[1].strip()
    return first[:1].upper() + first[1:]


def _range_cell(impl, name: str, default) -> str:
    """The Range / type column: the randomization range when there is one."""
    if name in impl.param_ranges:
        lo, hi = impl.param_ranges[name]
        kind = "int" if isinstance(default, int) and not isinstance(default, bool) else "float"
        return f"{kind}, `({lo}, {hi})`"
    if name in impl.default_categorical:
        return " or ".join(f"`{v!r}`" for v in impl.default_categorical[name])
    if isinstance(default, bool):
        return "bool"
    if default is None:
        return "float or `None`"
    if isinstance(default, str):
        return "str"
    if isinstance(default, (list, tuple)):
        return "`[lo, hi]`"
    if isinstance(default, int):
        return "int"
    return "float"


def render() -> str:
    lines: list[str] = [BEGIN, ""]
    lines.append("<!-- Generated by utils/docs/_gen_tile_catalog.py. Do not edit by hand:")
    lines.append("     edit each tile module's PARAM_DOCS / DEFAULT_PARAMS / PARAM_RANGES")
    lines.append("     and re-run the script. A test fails if this block is stale. -->")
    lines.append("")
    for name in sorted(REGISTRY):
        impl = REGISTRY[name]
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append(_summary(name))
        lines.append("")
        lines.append(f"Speed multiplier used by the velocity map: `{impl.default_speed_scale}`.")
        lines.append("")
        lines.append("| Parameter | Default | Range / type | Description |")
        lines.append("|-----------|---------|--------------|-------------|")
        for param, default in impl.default_params.items():
            shown = "`None`" if default is None else f"`{default}`"
            description = impl.param_docs.get(param, "")
            lines.append(f"| `{param}` | {shown} | {_range_cell(impl, param, default)} | {description} |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit non-zero if the catalog is stale")
    args = parser.parse_args()

    text = DOC.read_text(encoding="utf-8")
    start, end = text.index(BEGIN), text.index(END) + len(END)
    updated = text[:start] + render() + text[end:]

    if args.check:
        if updated != text:
            print(
                f"{DOC.relative_to(REPO)} is out of date with the tile registry.\nRun: python utils/docs/_gen_tile_catalog.py",
                file=sys.stderr,
            )
            return 1
        print(f"{DOC.relative_to(REPO)} is up to date")
        return 0

    if updated == text:
        print(f"{DOC.relative_to(REPO)} already up to date")
    else:
        DOC.write_text(updated, encoding="utf-8")
        print(f"Wrote the tile catalog into {DOC.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
